const reveals=document.querySelectorAll('.reveal');
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});
reveals.forEach(el=>io.observe(el));
const topbar=document.getElementById('topbar');
window.addEventListener('scroll',()=>topbar.classList.toggle('scrolled',scrollY>30));
const glow=document.getElementById('cursorGlow');
window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
const menu=document.getElementById('menuBtn'),nav=document.getElementById('nav');
menu.addEventListener('click',()=>nav.classList.toggle('open'));
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
